### ISSUE TITLE
Плагин имеет уязвимость

### ISSUE THREAD

**Issue by Mrflaxe** [LEDev-ru/CreeperArrowEffects#1]
Просматривая код я понял, что ты при выпуске стрелы запускаешь TimerTask который каждый тик (либо промежуток из конфига) генерирует партиклы. Когда стрела во что-то врезается, ты ловишь ProjectileHitEvent и закрываешь таск на спавн партиклов.

Однако если подойти вплотную к блоку и выстрелить в него из лука, или арбалета, то стрела просто замрёт в этом блоке, а ивент ProjectileHitEvent не будет вызван. Таким образом если знать про эту уязвимость, можно создать серьёзную нагрузку на сервер, просто расстреливая в упор стены из лука с зачарованием на "бесконечность" (это необходимо, чтобы стрелы не подбирались после выстрела).

Для решения этой проблемы рекомендую создавать ещё один отложенный таск с задержкой, по истечению которого если стерла не столкнулась ни с каким препятствием, спавн партиклов всё равно прекращался.

**Comment by LEDev-ru** [comment]
> Для решения этой проблемы рекомендую создавать ещё один отложенный таск с задержкой, по истечению которого если стерла не столкнулась ни с каким препятствием, спавн партиклов всё равно прекращался.

Спасибо за рекомендацию по устранению уязвимости, будет исправлено 👌
